---
id: dbstudychugoku-28th
base_name: logical-replication-and-full-text-search
tags:
- rabbit
- postgresql
- ChugokuDB
- fts
- search
- pgroonga
- groonga
presentation_date: 2020-01-25
presentation_start_time: 16:20
presentation_end_time: 17:20
version: 2020.01.25.0
licenses:
- CC-BY-SA-4.0
- CC-BY-3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: 堀本 泰弘
  email: horimoto@clear-code.com
  rubygems_user: komainu8
  slideshare_user: 
  speaker_deck_user: 
